apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane
  namespace: argocd-platform

  annotations:
    argocd.argoproj.io/sync-wave: "60"

spec:
  project: platform

  source:
    repoURL: git@github.com:thelazyenginerd/argocd-control-plane.git
    targetRevision: main
    path: infrastructure/crossplane

  destination:
    server: https://kubernetes.default.svc
    namespace: crossplane-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
