apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespaces.yaml
  - projects/bootstrap.yaml
  - projects/platform.yaml
  - minio.yaml
  - stackgres-crds.yaml
  - stackgres.yaml
  - crossplane.yaml
