apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespaces.yaml
  - projects/bootstrap.yaml
  - projects/platform.yaml
  - minio.yaml
  - crossplane.yaml
  - cloudnative-pg.yaml
  - postgres-instance.yaml
