apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stackgres-operator-crds
  namespace: argocd

  annotations:
    argocd.argoproj.io/sync-wave: "35"

spec:
  project: platform

  source:
    repoURL: https://stackgres.io/downloads/stackgres-k8s/stackgres/helm/
    chart: stackgres-operator
    targetRevision: 1.18.6

    helm:
      releaseName: stackgres-operator
      skipCrds: false
      values: |
        deploy:
          operator: false
          restapi: false
          collector: false

  destination:
    server: https://kubernetes.default.svc
    namespace: stackgres

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
