apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stackgres
  namespace: argocd

  annotations:
    argocd.argoproj.io/sync-wave: "40"

spec:
  project: platform

  source:
    repoURL: https://stackgres.io/downloads/stackgres-k8s/stackgres/helm/
    chart: stackgres-operator
    targetRevision: 1.18.6

    helm:
      releaseName: stackgres-operator
      values: |
        stackgres:
          config:
            create: false

  destination:
    server: https://kubernetes.default.svc
    namespace: stackgres

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - SkipDryRunOnMissingResource=true
