apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: storage
  namespace: argocd-platform

  annotations:
    argocd.argoproj.io/sync-wave: "20"

spec:
  project: platform

  source:
    repoURL: https://github.com/thelazyenginerd/argocd-control-plane.git
    targetRevision: main
    path: infrastructure/storage

  destination:
    server: https://kubernetes.default.svc
    namespace: minio

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
